Revised PR to publish PROMCODE machine readable files
oslc-op/website pull request #306
Opened 2022-01-21 02:35 UTC by tomkamimura

The stage of each file has been corrected.

2022-01-27 16:31 UTC, berezovskyi commented
Thank you @tomkamimura. May I ask if you ran ShapeChecker and if it produced any output? What flags did you use so that I can reproduce?

2022-01-27 16:31 UTC, berezovskyi commented
CC @jamsden so that he gets notifications for this PR.

2022-02-03 18:00 UTC, berezovskyi commented
ShapeCheck report:

<details>
<summary>Report</summary>

```
Results from ShapeChecker run on Thu Feb 03 18:55:44 CET 2022

Command line arguments:
   -t Warning -C -q undefinedShape -q unusedVocabulary -x http://open-services.net/ns/core -x
   http://open-services.net/ns/core#.* -x http://open-services.net/ns/promcode# -x
   http://open-services.net/ns/promcode##.* -v
   /Users/ezandbe/git/a/oslc/op/open-services/website/content/ns/promcode/promcode-vocab.ttl -s
   /Users/ezandbe/git/a/oslc/op/open-services/website/content/ns/promcode/promcode-shapes.ttl

A total of 55 issues were found (0 info, 48 warnings, 7 errors)

Checked vocabulary http://open-services.net/ns/promcode# from file:/Users/ezandbe/git/a/oslc/op/open-services/website/content/ns/promcode/promcode-vocab.ttl, with 33 issues (0 info, 33 warnings, 0 errors)
   While examining vocabulary term http://open-services.net/ns/promcode#raisedBy:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value raisedBy is a relation between an Issue resource and ManagedItem resources.
An Issue may be raised by one or more ManagedItem resources.)
   While examining vocabulary term http://open-services.net/ns/promcode#stateOfIssue:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value stateOfIssue is a relation between an Issue resource and a State resource.
The State resource defines a set of values which represent the state of an issue resource.)
   While examining vocabulary term http://open-services.net/ns/promcode#unitOfScopeItemSize:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: The description or comment should end with a period (full stop). (bad value unitOfScopeItemSize is a relation between a Project resource and a Unit resource.
It defines a unit of size which all the ScopeItem resources refer to in the project. )
   While examining vocabulary term http://open-services.net/ns/promcode#representedBy:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value representedBy is a relation between a WorkItem resource and a person in charge.
A work item may be represented by a person who acts as the contact for the work item.
This person is responsible for the progress of the work described by the WorkItem resource.
This person may or may not actually do the required work.)
   While examining vocabulary term http://open-services.net/ns/promcode#metricOfMeasure:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: The description or comment should end with a period (full stop). (bad value metricOfMeasure is a relation between a Measure resource and a Metric resource.
It defines a metric of Measure. )
   While examining vocabulary term http://open-services.net/ns/promcode#Risk:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value Risk is a subclass of ManagedItem. A Risk resource represents a potential problem that must be controlled in order to meet the objectives of a project. Shared risks between an acquirer and a supplier must be managed.
Internal risks which must be resolved by a supplier alone may not be shared.
Failure to control the potential problem may result in negative
consequences for the project, such as a schedule delay.)
   While examining vocabulary term http://open-services.net/ns/promcode#identifiedDate:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value identifiedDate is an optional property of a Risk resource.
It is the identified date of the Risk resource.
Its value is a dateTime.)
   While examining vocabulary term http://open-services.net/ns/promcode#plannedEndDate:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value plannedEndDate is either a property of a WorkItem resource or a Project resource.
It is the planned end date of the work described by the WorkItem resource or of the project described by the Project resource.
Its value is a dateTime.)
   While examining vocabulary term http://open-services.net/ns/promcode#collects:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value collects is a relation between a ManagedItemCollection resource and ManagedItem resources.
A Plan resource and a Report resource collect any combination of resources of ScopeItem, WorkItem and Artifact.
An IssueCollection resource collects only Issue resources and a RiskCollection collects only Risk resources.)
   While examining vocabulary term http://open-services.net/ns/promcode#ManagedItemCollection:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: The description or comment should end with a period (full stop). (bad value A ManagedItemCollection resource is a collection of ManagedItem resources of a specific interest.
A resource in the collection can be a resource of any subclass of ManagedItems, that is, ScopeItem, WorkItem, Artifact, Issue, or Risk.
ManagedItemCollection has four concrete subclasses which are Plan, Report, IssueCollection, and RiskCollection.
A ManagedItemCollection resource is linked to a Project resource it belongs to. )
   While examining vocabulary term http://open-services.net/ns/promcode#observes:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value observes is a relation between a Measurement resource and a Measure resource.
One Measurement observes zero or many Measures.)
   While examining vocabulary term http://open-services.net/ns/promcode#Report:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: The description or comment should end with a period (full stop). (bad value A Report resource represents a project status information reported by a supplier to an acquirer at agreed timing as a project report.
It is a ManagedItemCollection resource that collects ScopeItem resources, WorkItem resources, and Artifact resources whose properties are reported in the report.
It is also linked to Measurement resources that represent the quality data of the Artifact resources collected in the ManagedItemCollection resource. )
   While examining vocabulary term http://open-services.net/ns/promcode#identifiedBy:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value identifiedBy is a relation between a Risk resource and ManagedItem resources.
A Risk may be identified by one or more ManagedItem resources.)
   While examining vocabulary term http://open-services.net/ns/promcode#Plan:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: The description or comment should end with a period (full stop). (bad value A Plan resource is a collection of ScopeItem resources, WorkItem resources and Artifact resources with associated Measure resources. A Plan resource represents a project plan that is agreed on between an acquirer and a supplier at project initiation.
	Plan is a subclass of ManagedItemCollection. )
   While examining vocabulary term http://open-services.net/ns/promcode#plannedStartDate:
      Warning on http://www.w3.org/2000/01/rdf-schema#comment: White space after embedded newline - misuse of triple quotes? (bad value plannedStartDate is either a property of a WorkItem resource or of a Project resource.
It is the planned start date of the work described by the WorkItem resource or of the project described by the Project resource.
Its value is a dateTime.)
   While examining vocabulary term http://open-services.net/ns/promcode#raisedDate:
      Warning on http://www.w3.org/2000/01/rdf-schema#com [...]

2022-02-03 19:22 UTC, berezovskyi commented
@tomkamimura thank you for the PR. All looks good from my side.

@jamsden I think we can go ahead with the PR. ShapeChecker produces warnings on multiline strings, but those are not errors. Errors are raised on http://purl.org/dc/terms/, which is the correct namespace but does not provide RDF via conneg.

@ndjc Nick, if you could refresh my memory on how we dealt with incorrect dcterms namespace redirects, I would be very thankful!

2022-02-03 19:26 UTC, berezovskyi requested changes

2022-02-03 19:26 UTC, berezovskyi commented on content/ns/promcode/promcode-vocab.ttl
> +	dcterms:isPartOf <https://tools.oasis-open.org/version-control/browse/wsvn/oslc-promcode/shape/trunk/spec.html> ;
Should it be https://docs.oasis-open.org/oslc-promcode/promcode/v1.0/cs02/promcode-spec.html?

2022-02-03 19:26 UTC, berezovskyi commented on content/ns/promcode/promcode-vocab.ttl
> +	dcterms:issued "2021-03-23"^^<http://www.w3.org/2001/XMLSchema#date> ;
Should it be 2021-11-10? It says so on https://docs.oasis-open.org/oslc-promcode/promcode/v1.0/cs02/promcode-spec.html

2022-02-03 19:26 UTC, berezovskyi commented on content/ns/promcode/promcode-vocab.ttl
> +# 2 November 2021
I think this text above copyright can be removed to avoid confusion. Otherwise, please make sure it matches the Ontology resource contents.

2022-02-03 19:26 UTC, berezovskyi commented on content/ns/promcode/promcode-shapes.ttl
> +  dcterms:issued "2021-03-23"^^<http://www.w3.org/2001/XMLSchema#date> ;
same here, 2021-11-10?

2022-02-03 19:26 UTC, berezovskyi commented on content/ns/promcode/promcode-shapes.ttl
> +  dcterms:isPartOf <https://tools.oasis-open.org/version-control/browse/wsvn/oslc-promcode/shape/trunk/spec.html> ;
https://docs.oasis-open.org/oslc-promcode/promcode/v1.0/cs02/promcode-spec.html?

2022-02-03 19:26 UTC, berezovskyi commented on content/ns/promcode/promcode-shapes.ttl
> +# 2 November 2021
same here, can be removed

2022-02-04 02:30 UTC, tomkamimura commented on content/ns/promcode/promcode-vocab.ttl
> +	dcterms:isPartOf <https://tools.oasis-open.org/version-control/browse/wsvn/oslc-promcode/shape/trunk/spec.html> ;
I will fix it, cancel this PR and create a new PR with revised files.

2022-02-04 02:30 UTC, tomkamimura commented on content/ns/promcode/promcode-vocab.ttl
> +	dcterms:issued "2021-03-23"^^<http://www.w3.org/2001/XMLSchema#date> ;
I will fix it, cancel this PR and create a new PR with revised files.

2022-02-04 02:30 UTC, tomkamimura commented on content/ns/promcode/promcode-vocab.ttl
> +# 2 November 2021
I will fix it, cancel this PR and create a new PR with revised files.

2022-02-04 02:30 UTC, tomkamimura commented on content/ns/promcode/promcode-shapes.ttl
> +  dcterms:issued "2021-03-23"^^<http://www.w3.org/2001/XMLSchema#date> ;
I will fix it, cancel this PR and create a new PR with revised files.

2022-02-04 02:30 UTC, tomkamimura commented on content/ns/promcode/promcode-shapes.ttl
> +  dcterms:isPartOf <https://tools.oasis-open.org/version-control/browse/wsvn/oslc-promcode/shape/trunk/spec.html> ;
I will fix it, cancel this PR and create a new PR with revised files.

2022-02-04 02:30 UTC, tomkamimura commented on content/ns/promcode/promcode-shapes.ttl
> +# 2 November 2021
I will fix it, cancel this PR and create a new PR with revised files.

2022-02-04 02:31 UTC, closed without merging

2022-02-04 02:32 UTC, tomkamimura commented
I will update promcode-shapes.ttl and promocode-vocab.ttl and will create a new PR.

2022-02-04 07:06 UTC, berezovskyi commented on content/ns/promcode/promcode-vocab.ttl
> +	dcterms:isPartOf <https://tools.oasis-open.org/version-control/browse/wsvn/oslc-promcode/shape/trunk/spec.html> ;
Tom, no need for a new PR. Just push the fix commit to the same branch.