Updates to specifications and vocabulary content
oslc-op/website pull request #313
Opened 2023-08-09 18:37 UTC by jamsden

2023-08-09 18:39 UTC, jamsden commented
Updates for configuration management and tractor resource at oasis standards will be done as soon as they are published

2023-08-09 21:42 UTC, berezovskyi requested changes
Looks good except for the requested change on the table to recover old entries.

2023-08-09 21:42 UTC, berezovskyi commented on content/specifications/_index.md
> -| [Tracked Resource Set 3.0 PS01](https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/ps01/tracked-resource-set.html) |  **OSLC Open Project**  | Allows servers to expose a set of resources whose s
Please do not edit entries. All previously published versions should remain accessible. Instead, add new rows and move the old ones to the "Obsolete" table down below.

2023-08-10 13:01 UTC, jamsden commented on content/specifications/_index.md
> -| [Tracked Resource Set 3.0 PS01](https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/ps01/tracked-resource-set.html) |  **OSLC Open Project**  | Allows servers to expose a set of resources whose s
The obsolete table is full of a lot of not very useful information that could be confusing to people looking for OSLC OP specifications. And in addition, the history of of published specifications is already managed by the specifications themselves with their previous version fields which have links to the files on oasis. So this obsolete table seems redundant for many of those revised documents. What if we only include documents that are not part of published by oasis in this table?

2023-08-10 13:13 UTC, berezovskyi commented on content/specifications/_index.md
> -| [Tracked Resource Set 3.0 PS01](https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/ps01/tracked-resource-set.html) |  **OSLC Open Project**  | Allows servers to expose a set of resources whose s
I don't really share this view as I think that "Obsolete publications" heading removes any confusion. However, it's up to you and Jad to decide whether to remove the "Obsolete publications" table altogether. Until then, I suggest to keep tables updated as originally intended.

2023-08-10 15:03 UTC, berezovskyi approved these changes

2023-08-10 15:06 UTC, jamsden commented on content/specifications/_index.md
> -| [Tracked Resource Set 3.0 PS01](https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/ps01/tracked-resource-set.html) |  **OSLC Open Project**  | Allows servers to expose a set of resources whose s
fixed

2023-08-10 15:06 UTC, merged