feat: addding oslc-fest site content
oslc-op/website pull request #325
Opened 2024-10-02 15:46 UTC by isccarrasco

Hello guys, based on the meeting we have today with Michale, Kelly, @Jad-el-khoury (@jadelkhoury), @axelreichwein and I, I'm adding a folder that contains the `oslc-fest` website to this repository.
Please let me know if you need something else!
Regards!

2024-10-02 15:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oslc-op/website?pullRequest=325) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oslc-op/website?pullRequest=325) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oslc-op/website?pullRequest=325) it.</sub>

2024-10-02 15:52 UTC, jamsden approved these changes
This looks OK to me

2024-10-03 07:10 UTC, jadelkhoury commented
Hi!
Should we not add this content as a separate repository "oslcfest-site", or something?

2024-10-03 12:40 UTC, jamsden requested changes
As Jad suggests, let's move this content to a new repo. We will need to request OASIS to create this repo, and they may reject the request if it's not directly related to the OSLC-OP project sponsored work.

2025-05-30 21:49 UTC, berezovskyi commented
for the time being, we will use the 1-to-1 mirror under https://github.com/oslc-op/oslc-conf-website

closing for now

2025-05-30 21:49 UTC, closed without merging